/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projeto4;

public class App {

    public static void main(String[] args) {
        ClinicoGeral clinico = new ClinicoGeral("Jeferson", true, true);
        clinico.receitar();

        Cirurgiao cirurgiao = new Cirurgiao("Julia", true);
        cirurgiao.tratarPacience();
        cirurgiao.fazerIncisao();

        Medico medico = new Medico("Ronaldo", false);
        medico.tratarPacience();

        clinico.mostra();
        cirurgiao.mostra();
        medico.mostra();
    }
}
