/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testa.funcionarios;

public class App {
    public static void main(String[] args) {
        Gerente gerente = new Gerente("Zé Roberto", 19999.00, "zezinho", "123");
        Telefonista telefonista = new Telefonista("Joao", 2200, 12);
        Secretaria secretaria = new Secretaria("Joana", 3990, 1123242);
        gerente.mostraDados();
        telefonista.mostraDados();
        secretaria.mostraDados();
    }
}