/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projeto2;

public class App {

    public static void main(String[] args) {
        ContaBancaria normal = new ContaBancaria("Zezao", 1, 9800);
        ContaPoupanca poupanca = new ContaPoupanca("Leonardo", 2, 3200, 10);
        ContaEspecial especial = new ContaEspecial("Julia", 3, 3900, -500);

        normal.depositar(300);
        normal.sacar(9300);
        normal.mostra();

        poupanca.calcularNovoSaldo((float) 0.1);
        poupanca.sacar(200);
        poupanca.depositar(400);
        poupanca.mostra();

        especial.sacar(4400);
        especial.depositar(500);
        especial.mostra();


    }
}
