/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projeto3;

public class App {

    public static void main(String[] args) {
        ImovelNovo imv1 = new ImovelNovo(1, "Rua das Flores Nº193", 450000, 34000);
        ImovelUsado imv2 = new ImovelUsado(2, "Rua Francesco Dia Nº932", 900000, 90000);
        imv1.mostra();
        imv2.mostra();
    }
}
